[package]
name = "jito-bls-ncn-core"
description = "Jito's BLS NCN Core"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[features]
default = []
commonware = [
    "dep:commonware-cryptography",
    "dep:commonware-codec",
    "dep:commonware-utils",
    "dep:bytes",
    "dep:bn254",
    "dep:serde_json",
]

[dependencies]
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = { workspace = true }
bn254 = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
commonware-codec = { workspace = true, optional = true }
commonware-cryptography = { workspace = true, optional = true }
commonware-utils = { workspace = true, optional = true }
hex = { workspace = true }
# jito-restaking-core = { workspace = true }
# jito-vault-core = { workspace = true }
serde_json = { workspace = true, optional = true }
# jito-bytemuck = { workspace = true }
# bytemuck = { workspace = true }
solana-account-info = { workspace = true }
solana-bn254 = { workspace = true }
solana-keypair = { workspace = true }
solana-msg = { workspace = true }
solana-instruction = { workspace = true }
solana-program = { workspace = true }
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true }
solana-sha256-hasher = { workspace = true }
solana-signer = { workspace = true }
solana-system-interface = { workspace = true, features = ["bincode"] }
spl-associated-token-account-interface = { workspace = true }
spl-token-interface = { workspace = true }

[dev-dependencies]
bn254 = { workspace = true }
commonware-cryptography = { workspace = true }
