[package]
name = "jito-bls-ncn-program"
description = "Jito's BLS NCN Program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
name = "jito_bls_ncn_program"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
mainnet-beta = []
testnet = []
devnet = []
localhost = []

[dependencies]
solana-pubkey = { workspace = true }
solana-program = { workspace = true }
solana-security-txt = { workspace = true }
solana-account-info = { workspace = true }
solana-program-error = { workspace = true }
solana-program-entrypoint = { workspace = true }
jito-bls-ncn-core = { workspace = true }
solana-msg = { workspace = true }

[dev-dependencies]
